-- EcomDash2-owned baseline schema: marketing raw tables, email raw tables, and budget history.

CREATE TABLE IF NOT EXISTS raw_meta_ads_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  account_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adset_id TEXT NOT NULL DEFAULT '',
  adset_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  spend REAL NOT NULL DEFAULT 0,
  reach REAL NOT NULL DEFAULT 0,
  frequency REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  purchase_value REAL NOT NULL DEFAULT 0,
  add_to_cart REAL NOT NULL DEFAULT 0,
  initiate_checkout REAL NOT NULL DEFAULT 0,
  link_clicks REAL NOT NULL DEFAULT 0,
  landing_page_views REAL NOT NULL DEFAULT 0,
  campaign_status TEXT NOT NULL DEFAULT '',
  adset_status TEXT NOT NULL DEFAULT '',
  ad_status TEXT NOT NULL DEFAULT '',
  daily_budget REAL NOT NULL DEFAULT 0,
  raw_payload TEXT,
  view_content REAL NOT NULL DEFAULT 0,
  outbound_clicks REAL NOT NULL DEFAULT 0,
  video_3s_views REAL NOT NULL DEFAULT 0,
  video_15s_views REAL NOT NULL DEFAULT 0,
  video_p25_viewed REAL NOT NULL DEFAULT 0,
  video_p50_viewed REAL NOT NULL DEFAULT 0,
  video_p75_viewed REAL NOT NULL DEFAULT 0,
  video_p100_viewed REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, account_id, ad_id)
);

CREATE TABLE IF NOT EXISTS raw_meta_ads_segments_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  account_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adset_id TEXT NOT NULL DEFAULT '',
  adset_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  sessions REAL NOT NULL DEFAULT 0,
  add_to_cart REAL NOT NULL DEFAULT 0,
  initiate_checkout REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  spend REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, account_id, ad_id, country, device)
);

CREATE TABLE IF NOT EXISTS raw_meta_creatives (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  creative_id TEXT NOT NULL,
  ad_id TEXT NOT NULL DEFAULT '',
  thumbnail_url TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  headline TEXT NOT NULL DEFAULT '',
  primary_text TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  call_to_action TEXT NOT NULL DEFAULT '',
  destination_url TEXT NOT NULL DEFAULT '',
  format TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (workspace_id, creative_id)
);

CREATE TABLE IF NOT EXISTS raw_google_ads_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  customer_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  ad_group_id TEXT NOT NULL DEFAULT '',
  ad_group_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  cost REAL NOT NULL DEFAULT 0,
  conversions REAL NOT NULL DEFAULT 0,
  conversion_value REAL NOT NULL DEFAULT 0,
  daily_budget REAL NOT NULL DEFAULT 0,
  raw_payload TEXT,
  all_conversions REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, customer_id, ad_id)
);

CREATE TABLE IF NOT EXISTS raw_google_ads_segments_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  customer_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  ad_group_id TEXT NOT NULL DEFAULT '',
  ad_group_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  sessions REAL NOT NULL DEFAULT 0,
  add_to_cart REAL NOT NULL DEFAULT 0,
  initiate_checkout REAL NOT NULL DEFAULT 0,
  conversions REAL NOT NULL DEFAULT 0,
  conversion_value REAL NOT NULL DEFAULT 0,
  cost REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, customer_id, ad_id, country, device)
);

CREATE TABLE IF NOT EXISTS raw_tiktok_ads_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  advertiser_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adgroup_id TEXT NOT NULL DEFAULT '',
  adgroup_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  spend REAL NOT NULL DEFAULT 0,
  reach REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  purchase_value REAL NOT NULL DEFAULT 0,
  conversions REAL NOT NULL DEFAULT 0,
  cost_per_conversion REAL NOT NULL DEFAULT 0,
  daily_budget REAL NOT NULL DEFAULT 0,
  raw_payload TEXT,
  video_3s_views REAL NOT NULL DEFAULT 0,
  video_15s_views REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, advertiser_id, ad_id)
);

CREATE TABLE IF NOT EXISTS raw_tiktok_ads_segments_daily (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  advertiser_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adgroup_id TEXT NOT NULL DEFAULT '',
  adgroup_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  sessions REAL NOT NULL DEFAULT 0,
  add_to_cart REAL NOT NULL DEFAULT 0,
  initiate_checkout REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  purchase_value REAL NOT NULL DEFAULT 0,
  spend REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, advertiser_id, ad_id, country, device)
);

CREATE TABLE IF NOT EXISTS raw_klaviyo_campaigns (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL,
  campaign_name TEXT NOT NULL DEFAULT '',
  send_date TEXT NOT NULL DEFAULT '',
  sends REAL NOT NULL DEFAULT 0,
  delivered REAL NOT NULL DEFAULT 0,
  opens REAL NOT NULL DEFAULT 0,
  unique_opens REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  unique_clicks REAL NOT NULL DEFAULT 0,
  bounces REAL NOT NULL DEFAULT 0,
  unsubscribes REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, campaign_id, send_date)
);

CREATE TABLE IF NOT EXISTS raw_klaviyo_flows (
  workspace_id TEXT NOT NULL,
  _synced_at TEXT NOT NULL DEFAULT '',
  flow_id TEXT NOT NULL,
  flow_name TEXT NOT NULL DEFAULT '',
  send_date TEXT NOT NULL DEFAULT '',
  sends REAL NOT NULL DEFAULT 0,
  delivered REAL NOT NULL DEFAULT 0,
  opens REAL NOT NULL DEFAULT 0,
  unique_opens REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  unique_clicks REAL NOT NULL DEFAULT 0,
  bounces REAL NOT NULL DEFAULT 0,
  unsubscribes REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, flow_id, send_date)
);

CREATE TABLE IF NOT EXISTS budget_history (
  workspace_id TEXT NOT NULL,
  platform TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  effective_date TEXT NOT NULL,
  daily_budget REAL NOT NULL DEFAULT 0,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (workspace_id, platform, campaign_id, effective_date)
);
