-- EcomDash2-owned baseline schema: facts, dimensions, reports, and contracts.

CREATE TABLE IF NOT EXISTS fact_ads_daily (
  workspace_id TEXT NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  platform TEXT NOT NULL DEFAULT '',
  account_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adset_id TEXT NOT NULL DEFAULT '',
  adset_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  creative_id TEXT NOT NULL DEFAULT '',
  spend REAL NOT NULL DEFAULT 0,
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  cpa REAL NOT NULL DEFAULT 0,
  roas REAL NOT NULL DEFAULT 0,
  campaign_status TEXT NOT NULL DEFAULT '',
  adset_status TEXT NOT NULL DEFAULT '',
  ad_status TEXT NOT NULL DEFAULT '',
  daily_budget REAL NOT NULL DEFAULT 0,
  view_content REAL NOT NULL DEFAULT 0,
  outbound_clicks REAL NOT NULL DEFAULT 0,
  video_3s_views REAL NOT NULL DEFAULT 0,
  video_15s_views REAL NOT NULL DEFAULT 0,
  video_p25_viewed REAL NOT NULL DEFAULT 0,
  video_p50_viewed REAL NOT NULL DEFAULT 0,
  video_p75_viewed REAL NOT NULL DEFAULT 0,
  video_p100_viewed REAL NOT NULL DEFAULT 0,
  all_conversions REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, platform, account_id, ad_id)
);

CREATE TABLE IF NOT EXISTS fact_ads_segments_daily (
  workspace_id TEXT NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  platform TEXT NOT NULL DEFAULT '',
  account_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  adset_id TEXT NOT NULL DEFAULT '',
  adset_name TEXT NOT NULL DEFAULT '',
  ad_id TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  audience_segment TEXT NOT NULL DEFAULT '',
  brand_segment TEXT NOT NULL DEFAULT '',
  spend REAL NOT NULL DEFAULT 0,
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  sessions REAL NOT NULL DEFAULT 0,
  add_to_cart REAL NOT NULL DEFAULT 0,
  initiate_checkout REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  cpm REAL NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  cvr REAL NOT NULL DEFAULT 0,
  cpa REAL NOT NULL DEFAULT 0,
  roas REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, platform, account_id, ad_id, country, device)
);

CREATE TABLE IF NOT EXISTS fact_orders (
  workspace_id TEXT NOT NULL,
  order_id TEXT NOT NULL,
  order_date TEXT NOT NULL DEFAULT '',
  order_date_local TEXT NOT NULL DEFAULT '',
  customer_id TEXT NOT NULL DEFAULT '',
  total_revenue REAL NOT NULL DEFAULT 0,
  subtotal REAL NOT NULL DEFAULT 0,
  tax REAL NOT NULL DEFAULT 0,
  discounts REAL NOT NULL DEFAULT 0,
  total_refunded REAL NOT NULL DEFAULT 0,
  net_revenue REAL NOT NULL DEFAULT 0,
  item_count REAL NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT '',
  utm_source TEXT NOT NULL DEFAULT '',
  utm_medium TEXT NOT NULL DEFAULT '',
  utm_campaign TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  is_first_order REAL NOT NULL DEFAULT 0,
  shipping_cost REAL NOT NULL DEFAULT 0,
  payment_fees REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, order_id)
);

CREATE TABLE IF NOT EXISTS fact_order_items (
  workspace_id TEXT NOT NULL,
  line_item_id TEXT NOT NULL,
  order_id TEXT NOT NULL DEFAULT '',
  order_date TEXT NOT NULL DEFAULT '',
  product_id TEXT NOT NULL DEFAULT '',
  variant_id TEXT NOT NULL DEFAULT '',
  sku TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  variant_name TEXT NOT NULL DEFAULT '',
  quantity REAL NOT NULL DEFAULT 0,
  unit_price REAL NOT NULL DEFAULT 0,
  line_total REAL NOT NULL DEFAULT 0,
  discount REAL NOT NULL DEFAULT 0,
  unit_cost REAL NOT NULL DEFAULT 0,
  line_cost REAL NOT NULL DEFAULT 0,
  gross_profit REAL NOT NULL DEFAULT 0,
  margin_pct REAL NOT NULL DEFAULT 0,
  qty_refunded REAL NOT NULL DEFAULT 0,
  refund_amount REAL NOT NULL DEFAULT 0,
  net_quantity REAL NOT NULL DEFAULT 0,
  net_line_total REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, line_item_id)
);

CREATE TABLE IF NOT EXISTS dim_creative (
  workspace_id TEXT NOT NULL,
  creative_id TEXT NOT NULL,
  ad_id TEXT NOT NULL DEFAULT '',
  platform TEXT NOT NULL DEFAULT '',
  thumbnail_url TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  headline TEXT NOT NULL DEFAULT '',
  primary_text TEXT NOT NULL DEFAULT '',
  format TEXT NOT NULL DEFAULT '',
  landing_page TEXT NOT NULL DEFAULT '',
  first_seen TEXT NOT NULL DEFAULT '',
  last_seen TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (workspace_id, creative_id)
);

CREATE TABLE IF NOT EXISTS report_klaviyo_campaigns (
  workspace_id TEXT NOT NULL,
  campaign_id TEXT NOT NULL,
  campaign_name TEXT NOT NULL DEFAULT '',
  send_date TEXT NOT NULL DEFAULT '',
  sends REAL NOT NULL DEFAULT 0,
  delivered REAL NOT NULL DEFAULT 0,
  opens REAL NOT NULL DEFAULT 0,
  unique_opens REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  unique_clicks REAL NOT NULL DEFAULT 0,
  bounces REAL NOT NULL DEFAULT 0,
  unsubscribes REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  open_rate REAL NOT NULL DEFAULT 0,
  click_rate REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  bounce_rate REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, campaign_id, send_date)
);

CREATE TABLE IF NOT EXISTS report_klaviyo_flows (
  workspace_id TEXT NOT NULL,
  flow_id TEXT NOT NULL,
  flow_name TEXT NOT NULL DEFAULT '',
  send_date TEXT NOT NULL DEFAULT '',
  sends REAL NOT NULL DEFAULT 0,
  delivered REAL NOT NULL DEFAULT 0,
  opens REAL NOT NULL DEFAULT 0,
  unique_opens REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  unique_clicks REAL NOT NULL DEFAULT 0,
  bounces REAL NOT NULL DEFAULT 0,
  unsubscribes REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  open_rate REAL NOT NULL DEFAULT 0,
  click_rate REAL NOT NULL DEFAULT 0,
  ctr REAL NOT NULL DEFAULT 0,
  bounce_rate REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, flow_id, send_date)
);

CREATE TABLE IF NOT EXISTS contract_daily_overview (
  workspace_id TEXT NOT NULL,
  date TEXT NOT NULL,
  total_revenue REAL NOT NULL DEFAULT 0,
  total_orders REAL NOT NULL DEFAULT 0,
  aov REAL NOT NULL DEFAULT 0,
  total_spend REAL NOT NULL DEFAULT 0,
  mer REAL NOT NULL DEFAULT 0,
  blended_roas REAL NOT NULL DEFAULT 0,
  new_customers REAL NOT NULL DEFAULT 0,
  returning_customers REAL NOT NULL DEFAULT 0,
  cogs REAL NOT NULL DEFAULT 0,
  gross_profit REAL NOT NULL DEFAULT 0,
  net_profit_after_ads REAL NOT NULL DEFAULT 0,
  order_revenue REAL NOT NULL DEFAULT 0,
  total_refunded REAL NOT NULL DEFAULT 0,
  meta_spend REAL NOT NULL DEFAULT 0,
  meta_revenue REAL NOT NULL DEFAULT 0,
  google_spend REAL NOT NULL DEFAULT 0,
  google_revenue REAL NOT NULL DEFAULT 0,
  tiktok_spend REAL NOT NULL DEFAULT 0,
  tiktok_revenue REAL NOT NULL DEFAULT 0,
  shipping_cost REAL NOT NULL DEFAULT 0,
  payment_fees REAL NOT NULL DEFAULT 0,
  shipping_data_points REAL NOT NULL DEFAULT 0,
  payment_fee_data_points REAL NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (workspace_id, date)
);

CREATE TABLE IF NOT EXISTS contract_daily_channel_campaign (
  workspace_id TEXT NOT NULL,
  date TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL DEFAULT '',
  campaign_name TEXT NOT NULL DEFAULT '',
  spend REAL NOT NULL DEFAULT 0,
  impressions REAL NOT NULL DEFAULT 0,
  clicks REAL NOT NULL DEFAULT 0,
  purchases REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT '',
  daily_budget REAL NOT NULL DEFAULT 0,
  view_content REAL NOT NULL DEFAULT 0,
  outbound_clicks REAL NOT NULL DEFAULT 0,
  video_3s_views REAL NOT NULL DEFAULT 0,
  video_15s_views REAL NOT NULL DEFAULT 0,
  video_p25_viewed REAL NOT NULL DEFAULT 0,
  video_p50_viewed REAL NOT NULL DEFAULT 0,
  video_p75_viewed REAL NOT NULL DEFAULT 0,
  video_p100_viewed REAL NOT NULL DEFAULT 0,
  all_conversions REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, platform, campaign_id, campaign_name)
);

CREATE TABLE IF NOT EXISTS contract_creative_performance (
  workspace_id TEXT NOT NULL,
  date TEXT NOT NULL,
  creative_id TEXT NOT NULL,
  thumbnail_url TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  format TEXT NOT NULL DEFAULT '',
  headline TEXT NOT NULL DEFAULT '',
  ad_name TEXT NOT NULL DEFAULT '',
  platform TEXT NOT NULL DEFAULT '',
  total_spend REAL NOT NULL DEFAULT 0,
  total_purchases REAL NOT NULL DEFAULT 0,
  revenue REAL NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT '',
  impressions REAL NOT NULL DEFAULT 0,
  view_content REAL NOT NULL DEFAULT 0,
  outbound_clicks REAL NOT NULL DEFAULT 0,
  video_3s_views REAL NOT NULL DEFAULT 0,
  video_15s_views REAL NOT NULL DEFAULT 0,
  video_p25_viewed REAL NOT NULL DEFAULT 0,
  video_p50_viewed REAL NOT NULL DEFAULT 0,
  video_p75_viewed REAL NOT NULL DEFAULT 0,
  video_p100_viewed REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (workspace_id, date, creative_id, ad_name, platform)
);
